highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
fenced_code_blocks:  true

# Permalinks
permalink: /blog/:year/:month/:day/:title

# whoami
author:
    name:           Ivana Kajic
    email:          i2kajic@uwaterloo.ca

